# ==============================================================================
# OpenQuatt - Topology Substitutions Package: Duo
# ==============================================================================
substitutions:
  <<: !include duo.yaml
