# ==============================================================================
# OpenQuatt - Topology Substitutions Package: Single
# ==============================================================================
substitutions:
  <<: !include single.yaml
