# ==============================================================================
# OpenQuatt - Shared Substitutions Package
# ==============================================================================
substitutions:
  <<: !include oq_substitutions_common.yaml
